# frozen_string_literal: true

module Omml
  module Models
    autoload :Base, "omml/models/base"
    autoload :Registerable, "omml/models/registerable"

    autoload :CTAcc, "omml/models/ct_acc"
    autoload :CTAccPr, "omml/models/ct_acc_pr"
    autoload :CTAnchor, "omml/models/ct_anchor"
    autoload :CTAttr, "omml/models/ct_attr"
    autoload :CTBar, "omml/models/ct_bar"
    autoload :CTBarPr, "omml/models/ct_bar_pr"
    autoload :CTBookmark, "omml/models/ct_bookmark"
    autoload :CTBookmarkRange, "omml/models/ct_bookmark_range"
    autoload :CTBorder, "omml/models/ct_border"
    autoload :CTBorderBox, "omml/models/ct_border_box"
    autoload :CTBorderBoxPr, "omml/models/ct_border_box_pr"
    autoload :CTBox, "omml/models/ct_box"
    autoload :CTBoxPr, "omml/models/ct_box_pr"
    autoload :CTBr, "omml/models/ct_br"
    autoload :CTBreakBin, "omml/models/ct_break_bin"
    autoload :CTBreakBinSub, "omml/models/ct_break_bin_sub"
    autoload :CTCalendarType, "omml/models/ct_calendar_type"
    autoload :CTChar, "omml/models/ct_char"
    autoload :CTColor, "omml/models/ct_color"
    autoload :CTControl, "omml/models/ct_control"
    autoload :CTCtrlPr, "omml/models/ct_ctrl_pr"
    autoload :CTCustomXmlPr, "omml/models/ct_custom_xml_pr"
    autoload :CTCustomXmlRun, "omml/models/ct_custom_xml_run"
    autoload :CTD, "omml/models/ct_d"
    autoload :CTDPr, "omml/models/ct_d_pr"
    autoload :CTDataBinding, "omml/models/ct_data_binding"
    autoload :CTDecimalNumber, "omml/models/ct_decimal_number"
    autoload :CTDrawing, "omml/models/ct_drawing"
    autoload :CTEastAsianLayout, "omml/models/ct_east_asian_layout"
    autoload :CTEffectExtent, "omml/models/ct_effect_extent"
    autoload :CTEm, "omml/models/ct_em"
    autoload :CTEmpty, "omml/models/ct_empty"
    autoload :CTEqArr, "omml/models/ct_eq_arr"
    autoload :CTEqArrPr, "omml/models/ct_eq_arr_pr"
    autoload :CTF, "omml/models/ct_f"
    autoload :CTFPr, "omml/models/ct_f_pr"
    autoload :CTFType, "omml/models/ct_f_type"
    autoload :CTFFCheckBox, "omml/models/ct_ff_check_box"
    autoload :CTFFData, "omml/models/ct_ff_data"
    autoload :CTFFHelpText, "omml/models/ct_ff_help_text"
    autoload :CTFFName, "omml/models/ct_ff_name"
    autoload :CTFFStatusText, "omml/models/ct_ff_status_text"
    autoload :CTFFTextInput, "omml/models/ct_ff_text_input"
    autoload :CTFFTextType, "omml/models/ct_ff_text_type"
    autoload :CTFFDDList, "omml/models/ct_ffdd_list"
    autoload :CTFitText, "omml/models/ct_fit_text"
    autoload :CTFldChar, "omml/models/ct_fld_char"
    autoload :CTFonts, "omml/models/ct_fonts"
    autoload :CTFtnEdnRef, "omml/models/ct_ftn_edn_ref"
    autoload :CTFunc, "omml/models/ct_func"
    autoload :CTFuncPr, "omml/models/ct_func_pr"
    autoload :CTGraphicalObject, "omml/models/ct_graphical_object"
    autoload :CTGraphicalObjectData, "omml/models/ct_graphical_object_data"
    autoload :CTGraphicalObjectFrameLocking,
             "omml/models/ct_graphical_object_frame_locking"
    autoload :CTGroupChr, "omml/models/ct_group_chr"
    autoload :CTGroupChrPr, "omml/models/ct_group_chr_pr"
    autoload :CTHighlight, "omml/models/ct_highlight"
    autoload :CTHpsMeasure, "omml/models/ct_hps_measure"
    autoload :CTHyperlink, "omml/models/ct_hyperlink"
    autoload :CTInline, "omml/models/ct_inline"
    autoload :CTInteger2, "omml/models/ct_integer2"
    autoload :CTInteger255, "omml/models/ct_integer255"
    autoload :CTLang, "omml/models/ct_lang"
    autoload :CTLanguage, "omml/models/ct_language"
    autoload :CTLimLoc, "omml/models/ct_lim_loc"
    autoload :CTLimLow, "omml/models/ct_lim_low"
    autoload :CTLimLowPr, "omml/models/ct_lim_low_pr"
    autoload :CTLimUpp, "omml/models/ct_lim_upp"
    autoload :CTLimUppPr, "omml/models/ct_lim_upp_pr"
    autoload :CTLock, "omml/models/ct_lock"
    autoload :CTM, "omml/models/ct_m"
    autoload :CTMPr, "omml/models/ct_m_pr"
    autoload :CTMacroName, "omml/models/ct_macro_name"
    autoload :CTManualBreak, "omml/models/ct_manual_break"
    autoload :CTMarkup, "omml/models/ct_markup"
    autoload :CTMarkupRange, "omml/models/ct_markup_range"
    autoload :CTMathPr, "omml/models/ct_math_pr"
    autoload :CTMC, "omml/models/ct_mc"
    autoload :CTMCPr, "omml/models/ct_mc_pr"
    autoload :CTMCS, "omml/models/ct_mcs"
    autoload :CTMoveBookmark, "omml/models/ct_move_bookmark"
    autoload :CTMR, "omml/models/ct_mr"
    autoload :CTNary, "omml/models/ct_nary"
    autoload :CTNaryPr, "omml/models/ct_nary_pr"
    autoload :CTNonVisualDrawingProps, "omml/models/ct_non_visual_drawing_props"
    autoload :CTNonVisualGraphicFrameProperties,
             "omml/models/ct_non_visual_graphic_frame_properties"
    autoload :CTOMath, "omml/models/ct_o_math"
    autoload :CTOMathArg, "omml/models/ct_o_math_arg"
    autoload :CTOMathArgPr, "omml/models/ct_o_math_arg_pr"
    autoload :CTOMathJc, "omml/models/ct_o_math_jc"
    autoload :CTOMathPara, "omml/models/ct_o_math_para"
    autoload :CTOMathParaPr, "omml/models/ct_o_math_para_pr"
    autoload :CTObject, "omml/models/ct_object"
    autoload :CTOfficeArtExtension, "omml/models/ct_office_art_extension"
    autoload :CTOfficeArtExtensionList,
             "omml/models/ct_office_art_extension_list"
    autoload :CTOnOff, "omml/models/ct_on_off"
    autoload :CTPTab, "omml/models/ct_p_tab"
    autoload :CTPerm, "omml/models/ct_perm"
    autoload :CTPermStart, "omml/models/ct_perm_start"
    autoload :CTPhant, "omml/models/ct_phant"
    autoload :CTPhantPr, "omml/models/ct_phant_pr"
    autoload :CTPicture, "omml/models/ct_picture"
    autoload :CTPictureBase, "omml/models/ct_picture_base"
    autoload :CTPlaceholder, "omml/models/ct_placeholder"
    autoload :CTPoint2D, "omml/models/ct_point2_d"
    autoload :CTPosH, "omml/models/ct_pos_h"
    autoload :CTPosV, "omml/models/ct_pos_v"
    autoload :CTPositiveSize2D, "omml/models/ct_positive_size2_d"
    autoload :CTProofErr, "omml/models/ct_proof_err"
    autoload :CTR, "omml/models/ct_r"
    autoload :CTRPr, "omml/models/ct_r_pr"
    autoload :CTRPrChange, "omml/models/ct_r_pr_change"
    autoload :CTRPrOriginal, "omml/models/ct_r_pr_original"
    autoload :CTRad, "omml/models/ct_rad"
    autoload :CTRadPr, "omml/models/ct_rad_pr"
    autoload :CTRel, "omml/models/ct_rel"
    autoload :CTRPR, "omml/models/ct_rpr"
    autoload :CTRuby, "omml/models/ct_ruby"
    autoload :CTRubyAlign, "omml/models/ct_ruby_align"
    autoload :CTRubyContent, "omml/models/ct_ruby_content"
    autoload :CTRubyPr, "omml/models/ct_ruby_pr"
    autoload :CTRunTrackChange, "omml/models/ct_run_track_change"
    autoload :CTSPre, "omml/models/ct_s_pre"
    autoload :CTSPrePr, "omml/models/ct_s_pre_pr"
    autoload :CTSSub, "omml/models/ct_s_sub"
    autoload :CTSSubPr, "omml/models/ct_s_sub_pr"
    autoload :CTSSubSup, "omml/models/ct_s_sub_sup"
    autoload :CTSSubSupPr, "omml/models/ct_s_sub_sup_pr"
    autoload :CTSSup, "omml/models/ct_s_sup"
    autoload :CTSSupPr, "omml/models/ct_s_sup_pr"
    autoload :CTScript, "omml/models/ct_script"
    autoload :CTSdtComboBox, "omml/models/ct_sdt_combo_box"
    autoload :CTSdtContentRun, "omml/models/ct_sdt_content_run"
    autoload :CTSdtDate, "omml/models/ct_sdt_date"
    autoload :CTSdtDateMappingType, "omml/models/ct_sdt_date_mapping_type"
    autoload :CTSdtDocPart, "omml/models/ct_sdt_doc_part"
    autoload :CTSdtDropDownList, "omml/models/ct_sdt_drop_down_list"
    autoload :CTSdtEndPr, "omml/models/ct_sdt_end_pr"
    autoload :CTSdtListItem, "omml/models/ct_sdt_list_item"
    autoload :CTSdtPr, "omml/models/ct_sdt_pr"
    autoload :CTSdtRun, "omml/models/ct_sdt_run"
    autoload :CTSdtText, "omml/models/ct_sdt_text"
    autoload :CTShd, "omml/models/ct_shd"
    autoload :CTShp, "omml/models/ct_shp"
    autoload :CTSignedHpsMeasure, "omml/models/ct_signed_hps_measure"
    autoload :CTSignedTwipsMeasure, "omml/models/ct_signed_twips_measure"
    autoload :CTSimpleField, "omml/models/ct_simple_field"
    autoload :CTSmartTagPr, "omml/models/ct_smart_tag_pr"
    autoload :CTSmartTagRun, "omml/models/ct_smart_tag_run"
    autoload :CTSpacingRule, "omml/models/ct_spacing_rule"
    autoload :CTString, "omml/models/ct_string"
    autoload :CTStyle, "omml/models/ct_style"
    autoload :CTSym, "omml/models/ct_sym"
    autoload :CTText, "omml/models/ct_text"
    autoload :CTTextEffect, "omml/models/ct_text_effect"
    autoload :CTTextScale, "omml/models/ct_text_scale"
    autoload :CTTopBot, "omml/models/ct_top_bot"
    autoload :CTTrackChange, "omml/models/ct_track_change"
    autoload :CTTrackChangeNumbering, "omml/models/ct_track_change_numbering"
    autoload :CTTwipsMeasure, "omml/models/ct_twips_measure"
    autoload :CTUnSignedInteger, "omml/models/ct_un_signed_integer"
    autoload :CTUnderline, "omml/models/ct_underline"
    autoload :CTVerticalAlignRun, "omml/models/ct_vertical_align_run"
    autoload :CTWordprocessingOnOff, "omml/models/ct_wordprocessing_on_off"
    autoload :CTWrapNone, "omml/models/ct_wrap_none"
    autoload :CTWrapPath, "omml/models/ct_wrap_path"
    autoload :CTWrapSquare, "omml/models/ct_wrap_square"
    autoload :CTWrapThrough, "omml/models/ct_wrap_through"
    autoload :CTWrapTight, "omml/models/ct_wrap_tight"
    autoload :CTWrapTopBottom, "omml/models/ct_wrap_top_bottom"
    autoload :CTXAlign, "omml/models/ct_x_align"
    autoload :CTYAlign, "omml/models/ct_y_align"
    autoload :CTWordprocessingEmpty,
             "omml/models/ct_wordprocessing_empty"
    autoload :CTWordprocessingText,
             "omml/models/ct_wordprocessing_text"

    autoload :OMath, "omml/models/o_math"
    autoload :OMathPara, "omml/models/o_math_para"

    autoload :EGContentRunContent, "omml/models/groups/eg_content_run_content"
    autoload :EGMathContent, "omml/models/groups/eg_math_content"
    autoload :EGOMathElements, "omml/models/groups/eg_o_math_elements"
    autoload :EGOMathMathElements, "omml/models/groups/eg_o_math_math_elements"
    autoload :EGOfficeArtExtensionList,
             "omml/models/groups/eg_office_art_extension_list"
    autoload :EGPContent, "omml/models/groups/eg_p_content"
    autoload :EGRPr, "omml/models/groups/eg_r_pr"
    autoload :EGRPrBase, "omml/models/groups/eg_r_pr_base"
    autoload :EGRPrContent, "omml/models/groups/eg_r_pr_content"
    autoload :EGRPrMath, "omml/models/groups/eg_r_pr_math"
    autoload :EGRangeMarkupElements,
             "omml/models/groups/eg_range_markup_elements"
    autoload :EGRubyContent, "omml/models/groups/eg_ruby_content"
    autoload :EGRunInnerContent, "omml/models/groups/eg_run_inner_content"
    autoload :EGRunLevelElts, "omml/models/groups/eg_run_level_elts"
    autoload :EGScriptStyle, "omml/models/groups/eg_script_style"
    autoload :EGWordRPr, "omml/models/groups/eg_word_r_pr"
    autoload :EGWordRunInnerContent,
             "omml/models/groups/eg_word_run_inner_content"
    autoload :EGWrapType, "omml/models/groups/eg_wrap_type"

    autoload :EnumString, "omml/models/simple_types/enum_string"
    autoload :HexBinary, "omml/models/simple_types/hex_binary"
    autoload :STAdjCoordinate, "omml/models/simple_types/st_adj_coordinate"
    autoload :STAlignH, "omml/models/simple_types/st_align_h"
    autoload :STAlignV, "omml/models/simple_types/st_align_v"
    autoload :STBorder, "omml/models/simple_types/st_border"
    autoload :STBrClear, "omml/models/simple_types/st_br_clear"
    autoload :STBrType, "omml/models/simple_types/st_br_type"
    autoload :STBreakBin, "omml/models/simple_types/st_break_bin"
    autoload :STBreakBinSub, "omml/models/simple_types/st_break_bin_sub"
    autoload :STCalendarType, "omml/models/simple_types/st_calendar_type"
    autoload :STCombineBrackets, "omml/models/simple_types/st_combine_brackets"
    autoload :STCoordinate, "omml/models/simple_types/st_coordinate"
    autoload :STDisplacedByCustomXml,
             "omml/models/simple_types/st_displaced_by_custom_xml"
    autoload :STEdGrp, "omml/models/simple_types/st_ed_grp"
    autoload :STEm, "omml/models/simple_types/st_em"
    autoload :STFType, "omml/models/simple_types/st_f_type"
    autoload :STFFTextType, "omml/models/simple_types/st_ff_text_type"
    autoload :STFldCharType, "omml/models/simple_types/st_fld_char_type"
    autoload :STGeomGuideName, "omml/models/simple_types/st_geom_guide_name"
    autoload :STHexColor, "omml/models/simple_types/st_hex_color"
    autoload :STHighlightColor, "omml/models/simple_types/st_highlight_color"
    autoload :STHint, "omml/models/simple_types/st_hint"
    autoload :STInfoTextType, "omml/models/simple_types/st_info_text_type"
    autoload :STInteger2, "omml/models/simple_types/st_integer2"
    autoload :STInteger255, "omml/models/simple_types/st_integer255"
    autoload :STJc, "omml/models/simple_types/st_jc"
    autoload :STLang, "omml/models/simple_types/st_lang"
    autoload :STLimLoc, "omml/models/simple_types/st_lim_loc"
    autoload :STLock, "omml/models/simple_types/st_lock"
    autoload :STOnOff, "omml/models/simple_types/st_on_off"
    autoload :STPTabAlignment, "omml/models/simple_types/st_p_tab_alignment"
    autoload :STPTabLeader, "omml/models/simple_types/st_p_tab_leader"
    autoload :STPTabRelativeTo, "omml/models/simple_types/st_p_tab_relative_to"
    autoload :STPositiveCoordinate,
             "omml/models/simple_types/st_positive_coordinate"
    autoload :STProofErr, "omml/models/simple_types/st_proof_err"
    autoload :STRelFromH, "omml/models/simple_types/st_rel_from_h"
    autoload :STRelFromV, "omml/models/simple_types/st_rel_from_v"
    autoload :STRubyAlign, "omml/models/simple_types/st_ruby_align"
    autoload :STScript, "omml/models/simple_types/st_script"
    autoload :STSdtDateMappingType,
             "omml/models/simple_types/st_sdt_date_mapping_type"
    autoload :STShd, "omml/models/simple_types/st_shd"
    autoload :STShp, "omml/models/simple_types/st_shp"
    autoload :STSpacingRule, "omml/models/simple_types/st_spacing_rule"
    autoload :STStyle, "omml/models/simple_types/st_style"
    autoload :STTextEffect, "omml/models/simple_types/st_text_effect"
    autoload :STTextScale, "omml/models/simple_types/st_text_scale"
    autoload :STTheme, "omml/models/simple_types/st_theme"
    autoload :STThemeColor, "omml/models/simple_types/st_theme_color"
    autoload :STTopBot, "omml/models/simple_types/st_top_bot"
    autoload :STUnderline, "omml/models/simple_types/st_underline"
    autoload :STVerticalAlignRun,
             "omml/models/simple_types/st_vertical_align_run"
    autoload :STWrapText, "omml/models/simple_types/st_wrap_text"
    autoload :STXAlign, "omml/models/simple_types/st_x_align"
    autoload :STYAlign, "omml/models/simple_types/st_y_align"
    autoload :Token, "omml/models/simple_types/token"
    autoload :UnsignedInt, "omml/models/simple_types/unsigned_int"
    autoload :UnsignedLong, "omml/models/simple_types/unsigned_long"

    def self.eager_load!
      constants.each { |name| const_get(name) }
      nil
    end
  end
end
